# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53020c401cffba62ccecc656391320e4983bb558d63a93944ff95a5e072240e7d30e9e8aa1af17f9bc5d10ec3e44f3fc345182797f07049ac5c1049c5940fe14

test:
  secret_key_base: e1c4aa0b9ee44054b4f56b2fac05f24f76b54254fd00e5434171e2c14dd710d0ba41b4aba81827775e629bbf4a14e8c801b52040b210097547bde296381cbd12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
